//Author: Johnathan Evans
package forum;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 * PanelPost.java - A JPanel of a empty post layout that accepts a ForumPost object and displays the content
 * @author Johnathan Evans
 * @version 1.4
 */
public class PanelPost extends javax.swing.JPanel {
    
    private ForumPost post;
    private ForumMain parentPanel;
    private BufferedImage image;
    private DBAccess db = new DBAccess();
    
    /**
     * Assigns variables and runs the panel generation functions
     * @param parentPanel
     * @param post
     */
    public PanelPost(ForumMain parentPanel, ForumPost post) {
        this.post = post;
        this.parentPanel = parentPanel;
        this.initComponents();
        this.generatePost();
    }
    
    /**
     * Generates the panel content using the ForumPost object
     */
    public void generatePost() {
       
        username.setText(post.getFullName()); //Sets the posters full name to the panel
        date.setText(post.getDate()); //Sets the post date to the panel
        
        // Checks if the current user is not an ADMIN
        if(parentPanel.currentUser.getUserLevel().equals("ADMIN")) {
            adminSettings();
        } else if(parentPanel.currentUser.getUserId() == post.getUserId()) {
            ownerSettings();
        } else {
            defaultSettings();
        }
    }
    
    private void ownerSettings() {
        reportPost.setVisible(false);
        approvePost.setVisible(false);
        if(post.getFlagged() == 1) {
            textPost.setForeground(Color.red);
            textPost.setText("Content removed until an admin reviews the post!");
        } else {
            textPost.setText(post.getMessage()); //Sets the post content to the panel
        }
    }
    
    private void adminSettings() {
        editPost.setVisible(false);
        reportPost.setVisible(false);
        approvePost.setVisible(false); //Hides the approve button
        if(post.getFlagged() == 1) {
            textPost.setText(post.getMessage());
            textPost.setBackground(Color.red);
            approvePost.setVisible(true);
        } else {
            textPost.setText(post.getMessage()); //Sets the post content to the panel        
        }
    }
    
    private void defaultSettings() {
        editPost.setVisible(false); //Hides the edit button
        deletePost.setVisible(false); //Hides the delete button
        approvePost.setVisible(false); //Hides the approve button
        if(post.getFlagged() == 1) {
            reportPost.setVisible(false);
            textPost.setForeground(Color.red);
            textPost.setText("Content removed until an admin reviews the post!");
        } else {
            textPost.setText(post.getMessage()); //Sets the post content to the panel
        }
    }
    
    public void editPost() {
        parentPanel.openEditPost(post);
    }
    
    /**
     * Reports a post, flagging the post in the database
     */
    public void reportPost() {
        db.reportPost(post.getPostId()); //Reports the post using the reportPost function sending the current post id
        parentPanel.openThread(post.getThreadId()); //Redirects the user back to the thread
    }
    
    public void deletePost() {
        db.removePost(post.getPostId()); //Removes the post in the database
        parentPanel.openThread(post.getThreadId()); //Redirects the user back to the thread
    }
    
    private void approvePost() {
        db.approvePost(post.getPostId());
        parentPanel.openThread(post.getThreadId()); //Redirects the user back to the thread
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        editPost = new javax.swing.JLabel();
        reportPost = new javax.swing.JLabel();
        approvePost = new javax.swing.JLabel();
        deletePost = new javax.swing.JLabel();
        textPost = new javax.swing.JTextArea();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forum/user.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, -1, -1));

        username.setText("Example Username");
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 28, -1, -1));

        date.setText("Example Date");
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 48, -1, -1));

        editPost.setText("Edit Post");
        editPost.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editPost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editPostMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                editPostMouseReleased(evt);
            }
        });
        jPanel2.add(editPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 86, -1, -1));

        reportPost.setForeground(new java.awt.Color(255, 0, 0));
        reportPost.setText("Report Post");
        reportPost.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportPost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                reportPostMouseReleased(evt);
            }
        });
        jPanel2.add(reportPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 106, -1, -1));

        approvePost.setForeground(new java.awt.Color(0, 215, 0));
        approvePost.setText("Approve");
        approvePost.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        approvePost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                approvePostMouseReleased(evt);
            }
        });
        jPanel2.add(approvePost, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 106, -1, -1));

        deletePost.setForeground(new java.awt.Color(255, 0, 0));
        deletePost.setText("Delete");
        deletePost.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletePost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deletePostMouseReleased(evt);
            }
        });
        jPanel2.add(deletePost, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 106, -1, -1));

        textPost.setEditable(false);
        textPost.setColumns(20);
        textPost.setLineWrap(true);
        textPost.setRows(5);
        textPost.setText("Example Post Text");
        textPost.setWrapStyleWord(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textPost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textPost)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deletePostMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletePostMouseReleased
        //When the delete button is clicked a dialog box confirming the deletion will pop up
        int deleteAnswer = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete?", "Warning", JOptionPane.YES_NO_OPTION);
        if(deleteAnswer == JOptionPane.YES_OPTION){
            deletePost();
        }
    }//GEN-LAST:event_deletePostMouseReleased

    private void approvePostMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approvePostMouseReleased
        int approveAnswer = JOptionPane.showConfirmDialog(this, "Are you sure you want to approve the post?", "Warning", JOptionPane.YES_NO_OPTION);
        if(approveAnswer == JOptionPane.YES_OPTION){
            approvePost();
        }
    }//GEN-LAST:event_approvePostMouseReleased

    private void reportPostMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportPostMouseReleased
        int reportAnswer = JOptionPane.showConfirmDialog(this, "Are you sure you want to report this post?", "Warning", JOptionPane.YES_NO_OPTION);
        if(reportAnswer == JOptionPane.YES_OPTION){
            reportPost();
        }
    }//GEN-LAST:event_reportPostMouseReleased

    private void editPostMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPostMouseReleased
        editPost();
    }//GEN-LAST:event_editPostMouseReleased

    private void editPostMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPostMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_editPostMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel approvePost;
    private javax.swing.JLabel date;
    private javax.swing.JLabel deletePost;
    private javax.swing.JLabel editPost;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel reportPost;
    private javax.swing.JTextArea textPost;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
