//Author: Johnathan Evans
package forum;

import javax.swing.JOptionPane;

/**
 * ViewEditPost.java - A JPanel that allows the user to edit a post
 * @author Johnathan Evans
 * @version 1.1
 */
public class ViewEditPost extends javax.swing.JPanel {

    private ForumPost post;
    private ForumMain parentPanel;
    
    /**
     * Creates new form ViewEditPost
     */
    public ViewEditPost(ForumMain parentPanel, ForumPost post) {
        this.post = post;
        this.parentPanel = parentPanel;
        initComponents();
        postMessage.setText(post.getMessage());
        
    }
    
    public void updatePost() {
        String message = postMessage.getText();
        OffensiveWordDetection detect = new OffensiveWordDetection();
        if(detect.checkOffensive(message)) {
            JOptionPane.showMessageDialog(this, "Offensive word detected!");
        } else {
            DBAccess db = new DBAccess();
            db.updatePost(postMessage.getText(), post.getPostId());
            parentPanel.openThread(post.getThreadId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        postMessage = new javax.swing.JTextArea();
        updatePost = new javax.swing.JButton();

        postMessage.setColumns(20);
        postMessage.setLineWrap(true);
        postMessage.setRows(5);
        postMessage.setWrapStyleWord(true);
        jScrollPane1.setViewportView(postMessage);

        updatePost.setText("Update Post");
        updatePost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                updatePostMouseReleased(evt);
            }
        });
        updatePost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updatePost)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updatePost)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updatePostMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatePostMouseReleased
        updatePost();
    }//GEN-LAST:event_updatePostMouseReleased

    private void updatePostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatePostActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea postMessage;
    private javax.swing.JButton updatePost;
    // End of variables declaration//GEN-END:variables
}
