//Author: Johnathan Evans
package forum;

import javax.swing.JOptionPane;

/**
 * ViewCreatePost.java - A JPanel view for creating a post to a thread
 * @author Johnathan Evans
 * @version 1.1
 */
public class ViewCreatePost extends javax.swing.JPanel {
    
    private int threadId;
    private ForumMain parentPanel;
    
    /**
     * Assigns variables and creates the JPanel content
     * @param parentPanel
     * @param threadId
     */
    public ViewCreatePost(ForumMain parentPanel, int threadId) {
        this.threadId = threadId;
        this.parentPanel = parentPanel;
        initComponents();
        
    }
    
    /**
     * Collects the user input and creates a new post in the database
     */
    public void createPost() {
        String message = newPostMessage.getText(); //Collects the user post message from the form
        OffensiveWordDetection detect = new OffensiveWordDetection();
        if(detect.checkOffensive(message)) {
            JOptionPane.showMessageDialog(this, "Offensive word detected!");
        } else {
            DBAccess db = new DBAccess(); //Creates a new database object
            db.uploadPost(threadId, parentPanel.currentUser.getUserId(), message); //Uploads the post using the uploadPost function
            parentPanel.openThread(threadId);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        newPostMessage = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        newPostMessage.setColumns(20);
        newPostMessage.setLineWrap(true);
        newPostMessage.setRows(5);
        newPostMessage.setWrapStyleWord(true);
        jScrollPane1.setViewportView(newPostMessage);

        jButton1.setText("Post Reply");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Runs createPost function when the create button is clicked and redirects the user
     * @param evt 
     */
    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        createPost();
    }//GEN-LAST:event_jButton1MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea newPostMessage;
    // End of variables declaration//GEN-END:variables
}
