//Author: Johnathan Evans
package forum;

import javax.swing.JOptionPane;

/**
 * ViewEditThread.java - A JPanel that allows the user to edit a thread
 * @author Johnathan Evans
 * @version 1.0
 */
public class ViewEditThread extends javax.swing.JPanel {
    
    private ForumThread thread;
    private ForumMain parentPanel;
    
    /**
     * Creates new form ViewEditThread
     */
    public ViewEditThread(ForumMain parentPanel, ForumThread thread) {
        this.thread = thread;
        this.parentPanel = parentPanel;
        initComponents();
        textTitle.setText(thread.getTitle());
        threadContent.setText(thread.getContent());
    }
    
    private void updateThread() {
        String title = textTitle.getText();
        String content = threadContent.getText();
        OffensiveWordDetection detect = new OffensiveWordDetection();
        if(detect.checkOffensive(content) || detect.checkOffensive(title)) {
            JOptionPane.showMessageDialog(this, "Offensive word detected!");
        } else {
            DBAccess db = new DBAccess();
            db.updateThread(thread.getThreadId(), textTitle.getText(), threadContent.getText());
            parentPanel.openThread(thread.getThreadId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        textTitle = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textContent = new javax.swing.JScrollPane();
        threadContent = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        labelTitle.setText("Thread Title:");

        jLabel1.setText("Thread Content:");

        threadContent.setColumns(20);
        threadContent.setLineWrap(true);
        threadContent.setRows(5);
        threadContent.setWrapStyleWord(true);
        textContent.setViewportView(threadContent);

        jButton1.setText("Update Thread");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
                    .addComponent(textTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitle)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textContent, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        updateThread();
    }//GEN-LAST:event_jButton1MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JScrollPane textContent;
    private javax.swing.JTextField textTitle;
    private javax.swing.JTextArea threadContent;
    // End of variables declaration//GEN-END:variables
}
