//Author: Andrew Southam
package menus;

import administration.Login;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author w15008457
 */
public class studentSelect extends javax.swing.JFrame {

    /**
     * Creates new form studentSelect
     */
    int UserID = 0;
    int studentID = 0;
    
    public studentSelect(int userID,int classID4) {
       this.UserID = userID;
       this.studentID = classID4;
        initComponents();
        setName();
        fillTable();
        userDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        lblLogo3 = new javax.swing.JLabel();
        lblUserLevel3 = new javax.swing.JLabel();
        btnLogout3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        back = new javax.swing.JButton();
        lblInformation = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        leaderboard = new javax.swing.JTable();
        UserDetails = new javax.swing.JLabel();
        studentName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(179, 218, 255));

        lblLogo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Additional/logo.png"))); // NOI18N
        lblLogo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblUserLevel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUserLevel3.setForeground(new java.awt.Color(5, 24, 42));
        lblUserLevel3.setText("TEACHER");

        btnLogout3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLogout3.setForeground(new java.awt.Color(5, 24, 42));
        btnLogout3.setText("Logout");
        btnLogout3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout3ActionPerformed(evt);
            }
        });

        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(5, 24, 42));
        back.setText("Back");
        back.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                backComponentHidden(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        lblInformation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInformation.setForeground(new java.awt.Color(200, 0, 0));
        lblInformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInformation.setText(" ");
        lblInformation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        leaderboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quiz Name", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        leaderboard.getTableHeader().setReorderingAllowed(false);
        leaderboard.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                leaderboardComponentAdded(evt);
            }
        });
        leaderboard.setAutoCreateRowSorter(true);
        jScrollPane2.setViewportView(leaderboard);

        UserDetails.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserDetails.setForeground(new java.awt.Color(5, 24, 42));
        UserDetails.setText("FName LName (UserID)");

        studentName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentName.setText("Student Name");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblLogo3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserLevel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserDetails))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout3)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(lblInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(back)
                                .addGap(73, 73, 73))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(UserDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUserLevel3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnLogout3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInformation)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(studentName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void userDetails() {

        String name = null;

        String sql = "SELECT FName, LName FROM UserDetails WHERE user_ID = ?";

        try {
            Connection conn = databaseconn.connectToDB();

            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, UserID);
            ResultSet userDetailsResults = pstmt.executeQuery();

            while (userDetailsResults.next()) {
                String Fname = userDetailsResults.getString("FName");
                String Lname = userDetailsResults.getString("LName");
                name = (Fname + " " + Lname);
            }
            UserDetails.setText(name + " (" + this.UserID + ")");
        } catch (SQLException e) {

        }
    }
    private void setName(){
        String name = null;

        String sql = "SELECT FName, LName FROM UserDetails WHERE user_ID = ?";

        try {
            Connection conn = databaseconn.connectToDB();

            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, studentID);
            ResultSet userDetailsResults = pstmt.executeQuery();

            while (userDetailsResults.next()) {
                String Fname = userDetailsResults.getString("FName");
                String Lname = userDetailsResults.getString("LName");
                name = (Fname + " " + Lname);
            }
            studentName.setText(name); 
        } catch (SQLException e) {

        }
    }

private void fillTable(){
    
    ArrayList<String> quizName = new ArrayList<String>();
    ArrayList<Integer> result = new ArrayList<Integer>();
    String sql = "SELECT quiz_ID, result FROM Results WHERE student_ID = ?";
    String sql2 = "SELECT title FROM Quiz WHERE quiz_ID = ?";
        try {
            Connection conn = databaseconn.connectToDB();
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, studentID);
            ResultSet rs = pstmt.executeQuery();
            while (rs.next()) {
            int quizID = rs.getInt("quiz_ID");
            result.add(rs.getInt("result"));
            
            PreparedStatement pstmt2 = conn.prepareStatement(sql2);
            pstmt2.setInt(1, quizID);
            ResultSet rs2 = pstmt2.executeQuery();
            while (rs2.next()) {
            quizName.add(rs2.getString("title"));
            }
        } 
            
        }
            catch (SQLException e) {

        }  
        for(int i = 0; i < quizName.size();i++){
            DefaultTableModel model = (DefaultTableModel) leaderboard.getModel();
            model.addRow(new Object[]{quizName.get(i),result.get(i)});
        }  
    
}
    String sql = "SELECT student_ID FROM StudentDetails";
    String sql2 = "SELECT  FName,LName FROM UserDetails WHERE user_ID = ?";
        
       
    
    private void btnLogout3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout3ActionPerformed
        for (Window w : java.awt.Window.getWindows()) {
            w.setVisible(false);
            w.dispose();
        }

        Login loginFrame = new Login();
        loginFrame.setLocationRelativeTo(null);
        loginFrame.setVisible(true);
    }//GEN-LAST:event_btnLogout3ActionPerformed

    private void backComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_backComponentHidden

    }//GEN-LAST:event_backComponentHidden

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void leaderboardComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_leaderboardComponentAdded

    }//GEN-LAST:event_leaderboardComponentAdded

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserDetails;
    private javax.swing.JButton back;
    private javax.swing.JButton btnLogout3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblInformation;
    private javax.swing.JLabel lblLogo3;
    private javax.swing.JLabel lblUserLevel3;
    private javax.swing.JTable leaderboard;
    private javax.swing.JLabel studentName;
    // End of variables declaration//GEN-END:variables
}
